to_drop_shopee = [
    'Alasan Pembatalan',
    'Status Pembatalan/ Pengembalian',
    'No. Resi',
    'Opsi Pengiriman',
    'Antar ke counter/ pick-up',
    'Pesanan Harus Dikirimkan Sebelum (Menghindari keterlambatan)',
    'Waktu Pengiriman Diatur',
    'Waktu Pembayaran Dilakukan',
    'Nama Produk',
    'Nomor Referensi SKU',
    'Nama Variasi',
    'Harga Awal',
    'Harga Setelah Diskon',
    'Jumlah',
    'Total Diskon',
    'Diskon Dari Penjual',
    'Diskon Dari Shopee',
    'Berat Produk',
    'Total Berat',
    'Voucher Ditanggung Penjual',
    'Cashback Koin',
    'Voucher Ditanggung Shopee',
    'Paket Diskon',
    'Paket Diskon (Diskon dari Shopee)',
    'Paket Diskon (Diskon dari Penjual)',
    'Potongan Koin Shopee',
    'Diskon Kartu Kredit',
    'Ongkos Kirim Dibayar oleh Pembeli',
    'Estimasi Potongan Biaya Pengiriman',
    'Ongkos Kirim Pengembalian Barang',
    'Total Pembayaran',
    'Perkiraan Ongkos Kirim',
    'Catatan dari Pembeli',
    'Catatan',
    'Username (Pembeli)',
    'Nama Penerima',
    'No. Telepon',
    'Alamat Pengiriman',
    'Kota/Kabupaten',
    'Provinsi',
    'Waktu Pesanan Selesai'
]