to_drop_tokopedia = [
            'Nomor',
            'Tanggal Pesanan Selesai',
            'Waktu Pesanan Selesai',
            'Tanggal Pesanan Dibatalkan',
            'Waktu Pesanan Dibatalkan',
            'Nama Produk',
            'Tipe Produk',
            'Catatan Produk Pembeli',
            'Catatan Produk Penjual',
            'Harga Awal (IDR)',
            'Diskon Produk (IDR)',
            'Jumlah Subsidi Tokopedia (IDR)',
            'Nilai Voucher Toko Terpakai (IDR)',
            'Jenis Voucher Toko Terpakai',
            'Kode Voucher Toko Yang Digunakan',
            'Biaya Pengiriman Tunai (IDR)',
            'Biaya Asuransi Pengiriman (IDR)',
            'Total Biaya Pengiriman (IDR)',
            'Total Penjualan (IDR)',
            'Total Penjualan (IDR)',
            'Nama Pembeli',
            'No Telp Pembeli',
            'Nama Penerima',
            'No Telp Penerima',
            'Alamat Pengiriman',
            'Kota',
            'Provinsi',
            'Nama Kurir',
            'Tipe Pengiriman (regular, same day, etc)',
            'No Resi / Kode Booking',
            'Tanggal Pengiriman Barang',
            'Waktu Pengiriman Barang',
            'Nama Campaign',
            'Bebas Ongkir',
            'COD'
]